name: supa_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get: 4.6.6
  localization:
    path: ../localization
  logging: ^1.2.0
  supabase_flutter: ^2.0.1
  utils:
    path: ../utils 

dev_dependencies:
  flutter_test:
    sdk: flutter
  pro_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
