name: utils
description: "Utils for the app"
version: 0.0.1

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pro_lints: ^2.0.2  

flutter: null